### PR TITLE
Fix path handling for metrics observe provider

### LINKED ISSUE #7044: 4.x: inconsistent metrics endpoint
Assuming the following dependencies:

```xml
<dependency>
    <groupId>io.helidon.nima.observe</groupId>
    <artifactId>helidon-nima-observe-metrics</artifactId>
</dependency>
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics</artifactId>
</dependency>
```

The following code serves metrics at `/observe/metrics`:

```java
routing.addFeature(ObserveFeature.create());
```

However the following code serves metrics at `/metrics`:

```java
routing.addFeature(ObserveFeature.builder()
                                 .addProvider(MetricsObserveProvider.create())
                                 .build());
```

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #7044 

1. Looks like a line was omitted from the `MetricsObserveProvider#register` method when it was first created that deals with this scenario. (At least it seems that way comparing to health.)
2. A stray `/` in the `MetricsFeature` ctor needed to go away.

Also requires adding a protected method to `MetricsFeature` for visibility.

### CODE REVIEW

File: nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java [hunk 1]
```diff
@@ -181,6 +181,11 @@ public void afterStop() {
         }
     }
 
+    @Override
+    protected void context(String context) {
+        super.context(context);
```
Comment (romain-grecourt) [inline nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java:186]: Is this left-over? this override doesn't do anything.

Comment (tjquinno) [reply nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java:186]: Except make the method visible within package to `MetricObserveProvider` (same as with health).

Comment (romain-grecourt) [reply nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java:186]: roger that.

**Review by romain-grecourt — APPROVED** [review]
