### PR TITLE
4.x: HTTP/2 Locally half-closed streams needs to be able to receive frames

### LINKED ISSUE #7498: HTTP/2 - Locally half-closed streams needs to be able to receive frames
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.x

----------

## Problem Description
Locally half-closed streams needs to be able to receive frames:
https://httpwg.org/specs/rfc9113.html#StreamStates

## Steps to reproduce
```java

@ServerTest
public class HalfClosedStreamsTest {

    private final int port;
    private final URI uri;

    HalfClosedStreamsTest(WebServer server) {
        this.port = server.port();
        uri = URI.create("http://localhost:" + port + "/test");
    }

    @SetUpRoute
    static void router(HttpRouting.Builder router) {
        Handler peerPortRturningHandler = (req, res) -> res.send(String.valueOf(req.remotePeer().port()));
        router.route(GET, "/test", peerPortRturningHandler)
                .route(Http2Route.route(POST, "/test", peerPortRturningHandler));
    }

    @Test
    void closeDataFrameAfterHandlerIsDone() {
        try (HttpClient client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(5))
                .version(HttpClient.Version.HTTP_2)
                .build()) {

            // Upgrade to http2 GET (jdk client doesn't support prior-knowledge)
            int expectedClientPort = getClientPort(client);

            PipedInputStream in = new PipedInputStream();
            PipedOutputStream out = new PipedOutputStream(in);

            HttpRequest.BodyPublisher bodyPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> in);

            // Force the client to send end-stream flagged data frame after server handler finished
            Thread.ofVirtual().start(() -> {
                try {
                    Thread.sleep(300);
                    out.close();
                } catch (IOException | InterruptedException e) {
                    throw new RuntimeException(e);
                }
            });

            var respPut = client.send(HttpRequest.newBuilder().POST(bodyPublisher).uri(uri).build(),
                                      HttpResponse.BodyHandlers.ofString());

            assertThat(respPut.statusCode(), is(200));
            assertThat(Integer.parseInt(respPut.body()), is(expectedClientPort));

            // Another call would either fail, or be executed on a new connection(different client port)
            // in case locally half-closed stream is dropped after handler finishes
            int latestClientPort = getClientPort(client);
            assertThat(latestClientPort, is(expectedClientPort));

        } catch (IOException | InterruptedException e) {
            throw new RuntimeException(e);
        }

    }

    private int getClientPort(HttpClient client) {
        HttpResponse<String> r = null;
        try {
            r = client.send(HttpRequest.newBuilder()
                                    .GET()
                                    .uri(uri).build(),
                            HttpResponse.BodyHandlers.ofString());
        } catch (IOException | InterruptedException e) {
            fail(e);
        }
        assertThat(r.statusCode(), is(200));
        assertTrue(r.body().matches("\\d+"));
        return Integer.parseInt(r.body());
    }
}
```

### PR DESCRIPTION
**Pull request by danielkec**
Fixes #7498

### CODE REVIEW

File: webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HalfClosedStreamsTest.java [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+import static io.helidon.http.Http.Method.GET;
+import static io.helidon.http.Http.Method.POST;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.is;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+import static org.junit.jupiter.api.Assertions.fail;
+
+@ServerTest
+public class HalfClosedStreamsTest {
```
Comment (tomas-langer) [inline webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HalfClosedStreamsTest.java:45]: please remove public...

**Review by tomas-langer — CHANGES_REQUESTED** [review]

**Review by tomas-langer — APPROVED** [review]
