### PR TITLE
4.x: Host header validation for server request

### LINKED ISSUE #9270: Helidon gives internal server error for an invalid host header
## Environment Details
* Helidon Version: 4.0.8
* Helidon SE or Helidon MP : Helidon MP
* JDK version: jdk 21
* OS: 
* Docker version (if applicable):

----------

curl -v http://localhost:8080/api/v1/oci/secret/full -H 'Host: w.localhost:808a'

Stack trace - 

```
Internal server error io.helidon.http.RequestException: For input string: "808a"
    at io.helidon.http.RequestException$Builder.build(RequestException.java:139) ~[helidon-http-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.unhandledError(ErrorHandlers.java:203) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.lambda$handleError$1(ErrorHandlers.java:182) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
    at io.helidon.webserver.http.ErrorHandlers.handleError(ErrorHandlers.java:181) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:118) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters.filter(Filters.java:83) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.HttpRoutingImpl.route(HttpRoutingImpl.java:73) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:357) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:194) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:165) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47) ~[helidon-common-task-4.0.8.jar:4.0.8]
    at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at java.lang.VirtualThread.run(VirtualThread.java:329) ~[?:?]\nCaused by: java.lang.NumberFormatException: For input string: "808a"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
    at io.helidon.common.uri.UriBuilderSupport$UriInfoCustomMethods.authority(UriBuilderSupport.java:69) ~[helidon-common-uri-4.0.8.jar:4.0.8]
    at io.helidon.common.uri.UriInfo$BuilderBase.authority(UriInfo.java:115) ~[helidon-common-uri-4.0.8.jar:4.0.8]
    at io.helidon.http.RequestedUriDiscoveryContext$Builder$RequestedUriDiscoveryContextImpl.uriInfo(RequestedUriDiscoveryContext.java:344) ~[helidon-http-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1ServerRequest.createUriInfo(Http1ServerRequest.java:226) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118) ~[helidon-common-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1ServerRequest.requestedUri(Http1ServerRequest.java:215) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.security.SecurityContextFilter.filter(SecurityContextFilter.java:63) ~[helidon-webserver-security-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.common.context.Contexts.runInContext(Contexts.java:117) ~[helidon-common-context-4.0.8.jar:4.0.8]
    at io.helidon.webserver.context.ContextRoutingFeature.filter(ContextRoutingFeature.java:50) ~[helidon-webserver-context-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters.executeFilters(Filters.java:87) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters.lambda$filter$0(Filters.java:83) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75) ~[helidon-webserver-4.0.8.jar:4.0.8]
```

Seems like it is not possible to intercept this call in the filters to validate the request. None of the ExceptionMappers are also getting called.

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #9270 

### Description
`Host` header is now fully validated according to the specification in server request. If invalid, a 400 is returned (bad request).

### CODE REVIEW

**Review by spericas — COMMENTED** [review]
What sort of performance impact can we expect from this validation?

**Review by danielkec — COMMENTED** [review]
Maybe we can mention new switch in the `performance-tuning.adoc`

**Comment by tomas-langer** [comment]
> Maybe we can mention new switch in the `performance-tuning.adoc`

The switch is deprecated for removal, so I would rather not.

**Review by danielkec — APPROVED** [review]

File: http/http/src/main/java/io/helidon/http/HostValidator.java [hunk 1]
```diff
@@ -0,0 +1,347 @@
...
+public final class HostValidator {
+    private static final Pattern IP_V4_PATTERN =
+            Pattern.compile("^([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})$");
+    private static final boolean[] HEXDIGIT = new boolean[256];
+    private static final boolean[] UNRESERVED = new boolean[256];
+    private static final boolean[] SUB_DELIMS = new boolean[256];
+
+    static {
+        // digits
+        for (int i = '0'; i <= '9'; i++) {
```
Comment (re-thc) [inline http/http/src/main/java/io/helidon/http/HostValidator.java:38]: Can we use `Arrays.fill` instead of the for loops? Likely faster (now or in the future) / cleaner.

**Comment by spericas** [comment]
> > What sort of performance impact can we expect from this validation?
> 
> If header validation is disabled, none (it is skipped as is all header validation). If header validation is enabled, then there will be an impact for sure, as it does a lot of validation. On the other hand this is required by the HTTP specification, so there is not much we can do about it.

We need a way to turn this off in certain cases, regardless of what spec states. I didn't get the deprecation of the switch.

**Comment by danielkec** [comment]
```
```

**Comment by danielkec** [comment]
RE @spericas: `validate-request-headers` turns it off, and we already have that in [perf tuning guide](https://helidon.io/docs/v4/mp/guides/performance-tuning)
```yaml
  protocols:
    "http_1_1":
      validate-request-headers: true|false
      validate-response-headers: true|false
```

**Comment by spericas** [comment]
> RE @spericas: `validate-request-headers` turns it off, and we already have that in [perf tuning guide](https://helidon.io/docs/v4/mp/guides/performance-tuning)
> 
> ```yaml
>   protocols:
>     "http_1_1":
>       validate-request-headers: true|false
>       validate-response-headers: true|false
> ```

Cool, I wasn't sure that flag would control this new validation too

File: http/http/src/main/java/io/helidon/http/HostValidator.java (hunk 1 above)
Comment (danielkec) [reply http/http/src/main/java/io/helidon/http/HostValidator.java:38]: Only difference would be an extra stack frame, it could be faster if unrolled manually since the static block probably won't be hot enough for JIT optimization. But there goes cleaness ...

Comment (re-thc) [reply http/http/src/main/java/io/helidon/http/HostValidator.java:38]: Aren't there intrinsics on `fill` or has that changed?

Comment (danielkec) [reply http/http/src/main/java/io/helidon/http/HostValidator.java:38]: AFAIK only `copyOf` and `equals`

**Review by spericas — APPROVED** [review]
I see validation guarded by existing headers flag
