### PR TITLE
Restore percentile and bucket data to JSON metrics output

### LINKED ISSUE #7848: 4.x Metrics JSON output lacks percentile and bucket entries
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The JSON output format (no longer required by MP metrics but retained as a nice feature in Helidon 4.x) omits percentile and bucket output from timers and distribution summaries (histograms).

## Steps to reproduce
Declare a timer (via a `@Timed` annotation in MP or 
```
Metrics.globalRegistry().getOrCreate(Timer.builder("myTimer"));
```
in an app.

Then retrieve the JSON metrics output using `curl -H "Accept: application/json"  'http://localhost:8080/observe/metrics'`. The output does not include any percentiles (which Helidon sets up by default) or buckets (which are not created unless the app code assigns them for the timer or distribution summary).

### PR DESCRIPTION
**Pull request by tjquinno**
### Description
Resolves #7848 

I had to rewrite the JSON metrics output code for 4.x but accidentally omitted the percentile and bucket output. (It's fine in the Prometheus/OpenMetrics output because we rely on the Micrometer Prometheus meter registry for that in 4.x.)

This PR adds the missing output back.

### Documentation

No impact (outside of already-in-progress metrics doc revs).

### CODE REVIEW

File: webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/JsonFormatter.java [hunk 1]
```diff
@@ -471,6 +475,42 @@ protected void apply(JsonObjectBuilder builder) {
                 builder.add(meterId.name(), sameNameBuilder);
             }
 
+            private void addDetails(HistogramSnapshot snapshot, Meter.Id childId, TimeUnit timeUnit) {
+                snapshot.percentileValues().forEach(vap ->
+                                                            sameNameBuilder
```
Comment (spericas) [inline webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/JsonFormatter.java:480]: IMO, all these new lines don't make this code fragment more readable. I would make this code a bit less sparse.

**Review by spericas — APPROVED** [review]
