### PR TITLE
OIDC Client credentials flow fix

### LINKED ISSUE #10578: OIDC Client credentials flow fails with IDCS
Client credentials flow fails when used with IDCS.

### PR DESCRIPTION
**Pull request by Verdent**
### Description
Fixes #10578

This PR introduces a new configuration option, `client-credentials.scope`, which enables setting a specific scope value for the client credentials flow. This option is required to be set when `idcs` identity server is used. 

### Documentation

None

### CODE REVIEW

**Review by tomas-langer — DISMISSED** [review]

File: security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/ClientCredentialsConfigBlueprint.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+/**
+ * Configuration of the OIDC client credentials flow.
+ */
+@Prototype.Blueprint
+@Prototype.Configured
+interface ClientCredentialsConfigBlueprint {
+
+    /**
+     * Scope used when obtaining access token in the client credentials flow.
+     * It is required to set when {@code server-type} is set as an {@code idcs}.
```
Comment (tomas-langer) [inline security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/ClientCredentialsConfigBlueprint.java]: is set as an `idcs`
should be
is set to `idcs`

**Review by tomas-langer — APPROVED** [review]
