### PR TITLE
4.x: small archetype issues

### LINKED ISSUE #7446: 4.x: small archetype issues
Minor issues found while testing the 4.0 archetypes:

database-mp
- [x] README says "that uses the dbclient API". This uses JPA.

quickstart-se
- [x] README: health URL uses `PORT` instead of 8080. This is different from all other urls in the README
- [x] pom has two copies of dependencies for helidon-webserver-observe-health and helidon-health-checks
- [x] Exception when test runs:
```
2023.08.24 11:05:46.430 Attempt to start in unexpected state state STARTED; ignored
java.lang.IllegalStateException
        at io.helidon.metrics.PeriodicExecutor.lambda$startExecutor$1(PeriodicExecutor.java:139)
        at io.helidon.metrics.PeriodicExecutor.sync(PeriodicExecutor.java:175)
        at io.helidon.metrics.PeriodicExecutor.startExecutor(PeriodicExecutor.java:124)
        at io.helidon.metrics.PeriodicExecutor.start(PeriodicExecutor.java:91)
        at io.helidon.metrics.RegistryFactory.start(RegistryFactory.java:199)
        at io.helidon.webserver.observe.metrics.MetricsFeature.beforeStart(MetricsFeature.java:166)
```

### PR DESCRIPTION
**Pull request by tvallin**
### Description

Fix  #7446

### Documentation

no impact

### CODE REVIEW

File: archetypes/helidon/src/main/archetype/se/common/files/src/test/java/__pkg__/MainIT.java.mustache [hunk 1]
```diff
@@ -1,11 +1,11 @@
 package {{package}};
 
-import io.helidon.webclient.http1.Http1Client;
-import io.helidon.webserver.testing.junit5.ServerTest;
+import io.helidon.webserver.testing.junit5.DirectClient;
+import io.helidon.webserver.testing.junit5.RoutingTest;
 
-@ServerTest
+@RoutingTest
```
Comment (romain-grecourt) [inline archetypes/helidon/src/main/archetype/se/common/files/src/test/java/__pkg__/MainIT.java.mustache:6]: Shouldn't the IT test use `@ServerTest` and the unit test use `@RoutingTest` ?

Comment (tvallin) [reply archetypes/helidon/src/main/archetype/se/common/files/src/test/java/__pkg__/MainIT.java.mustache]: Yes you are right, it was a workaround. It should not have been in the PR.

**Review by romain-grecourt — APPROVED** [review]
