### PR TITLE
Archetype : generate module-info file

### LINKED ISSUE #7226: Optionally gernerate module-info.java for helidon projects generated by cli
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.0-M1
* Helidon SE or Helidon MP
* JDK version: 21-ea+31
* OS: macos venture 14.1
* Docker version (if applicable): n/a

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
The helidon cli does not generate an example `module-info.java` file. This means users desiring to modularize their applications would be expected to supply their own.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
Running
```
helidon init --version 4.0.0-M1
```
generates an application without a `module-info.java` file.

### PR DESCRIPTION
**Pull request by tvallin**
fix #7226

### CODE REVIEW

File: archetypes/helidon/src/main/archetype/common/files/src/main/java/module-info.java.mustache [hunk 1]
```diff
@@ -0,0 +1,6 @@
+
+module {{package}} {
+{{#module-info}}
+{{.}}
```
Comment (romain-grecourt) [inline archetypes/helidon/src/main/archetype/common/files/src/main/java/module-info.java.mustache:4]: You should make the model just be the module names.
Also the let's rename `module-info` to just `modules`.


```
module {{package}} {
{{#modules}}
    require {{.}};
{{/modules}}
}
```

**Review by romain-grecourt — APPROVED** [review]

**Comment by romain-grecourt** [comment]
@tvallin Can you backport this to 3.x ? thanks.

**Comment by tvallin** [comment]
Sure, See #7252
