### PR TITLE
Broad changes to handle case properly in headers and parameters

### LINKED ISSUE #5149: All implementations of headers need to be case-insensitive
## Environment Details
* Helidon Version: 2.x, 3.x, 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Helidon contains several implementations of headers. Not all of them conform to HTTP's requirement that headers be case-insensitive.

We have a separate issue https://github.com/helidon-io/helidon/issues/4956 as well as internal Slack channel reports:
> I believe there's a bug in io.helidon.common.http.Parameters.toMap() in Helidon 2.5.1
It seems, 2 of the 5 implementations I could find don't preserve the case insensitivity of the keys.
This leads to not finding headers if they aren't cased by the client as we expect. This case-insensitivity is part of the http spec.
Here are the 5 places I could find:
> * HashParameters, ReadOnlyParameters, and UnmodifiableParameters in the common.http package
> * WebClientQueryParams, and WebClientRequestHeadersImpl in the webclient package
The two are: ReadOnlyParameters and WebClientRequestHeadersImpl

The afflicted implementations percolate into other, more directly visible places (potentially request headers, response headers, etc.). We need to review all.

## Steps to reproduce
For one, see the referenced issue about B3 headers in tracing.

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #5149

Header names should be _case-insensitive_. What Helidon calls "parameters"  (query parameter, path params) should be _case-sensitive_. (Note that our use of "parameters" in this context does not correspond to other usages such as  https://httpwg.org/specs/rfc9110.html#parameter, in which a parameter is an optional addition to the value of a "field"--basically, an addition to a header value.)

This PR fixes problems in both headers and parameters.

I tried to be fairly minimally-invasive as possible while still addressing the problems. Still, there are quite a few changes needed to fix this situation.

## Some highlights:

Key changes are in `helidon-common-http` but other components are affected as well.

* The new class `HashHeaders` extends `HashParameters`. Each now creates the correct type of `Map` (case-sensitive or -insensitive) in separate protected factory methods. Various classes related to writeable headers now extend `HashHeaders` (instead of extending `HashParameters` as they did before) and so now inherit the correct case-insensitive behavior.
* The new class `ReadOnlyHeaders` extends `ReadOnlyParameters`. Each now creates the correct type of `Map` in protected factory methods for various purposes. Various classes related to read-only headers now extend `ReadOnlyHeaders` to inherit the correct case-insensitive behavior.
* Several other classes are changed to use `Headers` or its various implementations rather than `Parameters` or its counterparts so the data is handled in the (correct) case-insensitive manner.
* Tests:
   * Lots of new tests check for the appropriate behavior in many classes related to headers and parameters. `helidon-config-testing` now contains a new `CaseSensitivityTester` utility class and is a new test-scoped dependency for several components.
   * A new tracing-specific test checks for proper B3 propagation from client to server.

## Some lower-level details:

`Parameters` now extends `Iterable<Map.Entry<String, List<String>>>` and provides a default implementation of `iterator`. Adding this `extends` reduces the need to create temporary data structures in other code. For our classes which implement `Parameters`, this PR includes overrides of `iterator` with more efficient code than the default.

I kept some methods that the IDE shows as no longer used because, although unlikely, developers might have written extensions of our classes and overridden those methods. Removing them would be a backwards-incompatible change.

There is abundant opportunity to--but I did not--refactor further to reduce even more code duplication. For example, 
* `Header` and `Parameters` could extend a common parameterized interface
* `HashParameters` and `HashHeaders`  could extend a common abstract superclass
* Same for `ReadOnlyParameters` and `ReadOnlyHeaders` 
 
 But doing that refactoring would be quite a bit more far-reaching than the proposed changes here. Plus, header handling is much different in 4.x so further major refactoring work in 3.x would not carry forward and is likely not worth the investment.

### CODE REVIEW

**Review by romain-grecourt — DISMISSED** [review]

File: common/http/src/main/java/io/helidon/common/http/ReadOnlyHeaders.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    /**
+     * Creates a new instance populated with the specified {@code Parameters} settings.
+     *
+     * @param initialContent {@code Parameters} to be used as the initial content for the new instance
+     * @return new instance with specified initial content
+     * @deprecated Use {@link #create(Headers)} instead, passing {@code Headers} instead of {@code Parameters}.
+     */
+    @Deprecated(since = "3.0.3", forRemoval = true)
```
Comment (tomas-langer) [inline common/http/src/main/java/io/helidon/common/http/ReadOnlyHeaders.java:62]: No need to deprecate, 4.0.0 will not use this class at all

**Review by tomas-langer — APPROVED** [review]
