### PR TITLE
4.x Add support for `@SpanAttribute` annotation, use entire path for REST resource span name

### LINKED ISSUE #8157: 4.x Add support for Otel `@SpanAttribute` annotation
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
As described in the OTel instrumentation doc [here](https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#adding-attributes-to-the-span-with-spanattribute) the `@SpanAttribute` annotation allows the developer to specify that each such annotated method parameter is to be added as an attribute to the telemetry span for that method. 

The MP telemetry spec specifically mentions this annotation in [its `@WithSpan` section](https://download.eclipse.org/microprofile/microprofile-telemetry-1.0/tracing/microprofile-telemetry-tracing-spec-1.0.html#_withspan).

Currently Helidon's MP telemetry implementation does not process `@SpanAttribute`.

### LINKED ISSUE #8162: 4.x OpenTelemetry span name includes only the last path segment, not the entire path
## Environment Details
* Helidon Version: 4.0.1
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
OpenTelemetry span names include only the last segment of the path, not the entire path.

This is a change from Helidon's prior OpenTracing behavior and seems to conflict with the OpenTelemetry semantic conventions for HTTP server-side [span naming](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name):
> HTTP server span names SHOULD be {method} {http.route}

`method` is the HTTP method (e.g., `GET`) and `http.route` is defined [here](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#http-server-semantic-conventions):
> The matched route, that is, the path template in the format used by the respective server framework.

## Steps to reproduce
1. Create a resource class with a `@Path`.
2. Add a subresource method with its own `@Path` specifying a subpath and with `@WithSpan`. 
The resulting span is named using only the last path segment, not the entire path.

### PR DESCRIPTION
**Pull request by tjquinno**
### Description
Resolves #8157 
Resolves #8162 

Highlights:
* Enhance `WithSpanInterceptor` so it also processes `@SpanAttribute` annotations.
* Add tests to check span name and attributes.
* Fix derivation of OTel span name for REST endpoints to reflect OpenTelemetry span naming semantic conventions.
* Add tests for REST endpoint span naming.

### Documentation
Bug fix; no doc impact.

### CODE REVIEW

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java [hunk 1]
```diff
@@ -163,6 +153,47 @@ public void filter(final ContainerRequestContext request, final ContainerRespons
...
+        //
+        // where a low-cardinality path would be, for example /greet/{name} rather than /greet/Joe, /greet/Dmitry, etc.
+
+        if (spanNameFullUrl) {
+            return requestContext.getMethod() + " " + requestContext.getUriInfo().getAbsolutePath().toString();
+        }
+        ExtendedUriInfo extendedUriInfo = (ExtendedUriInfo) requestContext.getUriInfo();
+
+        // Derive the original path (including path parameters) of the matched resource from the bottom up.
+        StringBuilder derivedPath = new StringBuilder();
```
Comment (ljnelson) [inline microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java:169]: Given all the `insert(0...)` work you're doing, maybe add things to a `Deque` instead and then flatten the `Deque` into a `StringBuilder` later. I'm not sure about `StringBuilder`'s innards but this might involve a heck of a lot of array copying and allocations. It also may not ultimately matter in the scheme of things but I'm thinking about cut-and-paste people down the line.

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java [hunk 2]
```diff
@@ -163,6 +153,47 @@ public void filter(final ContainerRequestContext request, final ContainerRespons
...
+
+    private String applicationPath() {
+        Application app = Contexts.context()
+                .flatMap(it -> it.get(Application.class))
+                .orElseThrow(() -> new IllegalStateException("Application missing from context"));
+
+        if (app == null) {
+            return "";
+        }
+        ApplicationPath applicationPath = getRealClass(app.getClass()).getAnnotation(ApplicationPath.class);
```
Comment (ljnelson) [inline microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java:193]: Since you've already used things like `ExtendedUriInfo` maybe there's a Jersey class that will give you whatever the `@ApplicationPath` annotation ends up setting indirectly?

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java [hunk 3]
```diff
@@ -75,19 +78,42 @@ public Object interceptSpan(InvocationContext context) throws Exception {
...
+                    spanBuilder.setAttribute(attrName, (String) pValue);
+                } else if (paramType.isAssignableFrom(long.class) || paramType.isAssignableFrom(Long.class)) {
+                    spanBuilder.setAttribute(attrName, (long) pValue);
+                } else if (paramType.isAssignableFrom(double.class) || paramType.isAssignableFrom(Double.class)) {
+                    spanBuilder.setAttribute(attrName, (double) pValue);
+                } else if (paramType.isAssignableFrom(boolean.class) || paramType.isAssignableFrom(Boolean.class)) {
+                    spanBuilder.setAttribute(attrName, (boolean) pValue);
+                } else {
+                    spanBuilder.setAttribute(attrName, pValue.toString());
+                }
```
Comment (ljnelson) [inline microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java:103]: I'm pretty sure these are backwards. You want `String.class.isAssignableFrom(paramType)`. Or you want to do something like:
```
switch (paramType) {
case Class<?> x when Long.class.isAssignableFrom(paramType): // this may? work for primitives too? can't remember if autoboxing kicks in?
  spanBuilder.setAttribute(attrName, x.cast(pValue));
  break;
case Class<?> x when Double.class.isAssignableFrom(paramType):
  spanBuilder.setAttribute(attrName, x.cast(pValue));
  break;
case Class<?> x when Boolean.class.isAssignableFrom(paramType):
  spanBuilder.setAttribute(attrName, x.cast(pValue));
  break;
default:
  spanBuilder.setAttribute(attrName, pValue.toString());
  break;
}
```

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java [hunk 4]
```diff
@@ -75,19 +78,42 @@ public Object interceptSpan(InvocationContext context) throws Exception {
...
+            }
+        }
+
+        // Start new Span
+        Span span = spanBuilder.startSpan();
 
         try (Scope scope = span.makeCurrent()) {
-            return context.proceed();
+            Object result = context.proceed();
+            span.end();
```
Comment (ljnelson) [inline microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java:112]: Double-checking you intended to hoist this out of the `finally` block.

**Review by ljnelson — CHANGES_REQUESTED** [review]
Got some assignability stuff backwards, I think; have a peek

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java (hunk 1 above)
Comment (tjquinno) [reply microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java:169]: Yes, `insert(0,...)` does some array copying. Changed.

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java (hunk 2 above)
Comment (tjquinno) [reply microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java:193]: I didn't see a way to do that, after quite some looking.

If you have a specific suggestion I'd welcome it but I didn't find one. The security code Tomas pointed to uses the same technique to get the `Application`.

File: microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java (hunk 4 above)
Comment (tjquinno) [reply microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java:112]: Very much so. There are two separate ways to end the span; one with an exception (see the `catch` code) and one without. Ending it in the `finally` block with no exception is _not_ correct.

**Review by ljnelson — DISMISSED** [review]
LGTM (not an expert in this area)

**Review by tomas-langer — APPROVED** [review]
LGTM
