### PR TITLE
Remove incorrect override of UriQuery.isEmpty in the impl class

### LINKED ISSUE #5929: `UriQueryImpl` incorrectly reports `isEmpty` as false always
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The `UriQuery` interface defines a default impl of `isEmpty()` as returning `size() == 0`.

But the only implementation, `UriQueryImpl`, overrides this and always returns `false`, even if the `UriQuery` is created with a null or empty query string.

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #5929 

Signed-off-by: tim.quinn@oracle.com <tim.quinn@oracle.com>

### CODE REVIEW

**Review by danielkec — APPROVED** [review]

File: common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java [hunk 1]
```diff
@@ -54,4 +54,13 @@ void testEncodedOtherChars() {
         assertThat(uriQuery.value("h"), is("xc#e<"));
         assertThat(uriQuery.value("a"), is("b&c=d"));
     }
+    
+    @Test
+    void testEmptyQueryString() {
+        UriQuery uriQuery = UriQuery.create(null);
```
Comment (tomas-langer) [inline common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java:60]: `UriQuery.create(null)` should not be supported and should throw a NPE.

**Review by tomas-langer — CHANGES_REQUESTED** [review]

File: common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java (hunk 1 above)
Comment (tjquinno) [reply common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java:60]: If you feel this strongly that null should not be allowed as the value for `UriQuery` then let's approve this very focused bug fix as-is and create a separate issue for null handling.

There are several places in `UriQueryImpl` (unchanged by this PR) that check for null and take relevant action, so the original author (!) seems to have considered this a valid use case and there could be code elsewhere that depends on this behavior. 

I would rather not expand the scope of _this_ bug fix to address other aspects of `UriQuery` that seem to be working as designed.

Comment (tomas-langer) [reply common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java:60]: The original author understands.

**Review by tomas-langer — APPROVED** [review]
