### PR TITLE
[4.x] Fix incorrect tags comparison when trying to match metric IDs

### LINKED ISSUE #5546: [4.x] MetricRegistry::counter inconsistent result with multiple tags
Backport of #5541 for Helidon 4.x

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #5546 

Forward-port of #5544 (see description there)

### CODE REVIEW

File: metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java [hunk 1]
```diff
@@ -56,4 +60,70 @@ void testConflictingMetadata() {
...
+        MetricStore store = MetricStore.create(REGISTRY_SETTINGS,
+                                               NoOpMetricRegistry.NO_OP_METRIC_FACTORIES,
+                                               null,
+                                               null,
+                                               MetricRegistry.Type.APPLICATION,
+                                               registry::toImpl);
+
+        Counter counter1 = store.getOrRegisterMetric(metadata, Counter.class, tags1);
+        Counter counter2 = store.getOrRegisterMetric(metadata, Counter.class, tags2);
+        assertThat("Counters with overlapping but different tags", counter1, not(is(counter2)));
```
Comment (tomas-langer) [inline metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java:127]: I would use either `is(not(` or just `not(` so the assertion reads like English sentence:
"assert that counter1 is not counter2" seems easier to understand than "assert that counter1 not is counter2"

**Review by tomas-langer — APPROVED** [review]
Small comment (nit pick...), in general LGTM
