### PR TITLE
Move MP config encryption from SE module.

### LINKED ISSUE #11096: 4.3.3 SE service is getting errors re: io.helidon.config.mp.spi from io.helidon.config.encryption
## Environment Details
* Helidon Version: 4.3.3
* Helidon SE 
* JDK version: 21.x
* OS: OL9

----------

## Problem Description

Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module io.helidon.config.encryption does not read a module that exports io.helidon.config.mp.spi

See here:
[INFO]    \- io.helidon.config:helidon-config-encryption:jar:4.3.3:compile
[INFO]       +- io.helidon.common:helidon-common-key-util:jar:4.3.3:compile
[INFO]       \- io.helidon.common:helidon-common-crypto:jar:4.3.3:compile

and yet config.mp is required.

See also:
https://github.com/helidon-io/helidon/blob/helidon-4.3.x/config/encryption/src/main/java/module-info.java
where line 30 has "requires static io.helidon.config.mp"
And line 39 where it provides a mp config filter.

## Steps to reproduce
Try to use helidon-config-encryption in a JPMS enabled module for Helidon SE 4.3.3.

### PR DESCRIPTION
**Pull request by tomas-langer**
### Description
Resolves #11096 

- remove dependency on MP APIs from `helidon-config-encryption`, as service implementation implies module dependency (i.e. `requires static` does not work)
- move MP config encryption to `helidon-config-mp` module, to keep backward compatibility (i.e. we do not need an additional module, and it is anyways included by `helidon-microprofile-config`)

### CODE REVIEW

File: config/config-mp/src/main/java/io/helidon/config/mp/MpEncryptionFilter.java [hunk 1]
```diff
@@ -14,15 +14,22 @@
  * limitations under the License.
  */
 
-package io.helidon.config.encryption;
+package io.helidon.config.mp;
```
Comment (romain-grecourt) [inline config/config-mp/src/main/java/io/helidon/config/mp/MpEncryptionFilter.java:17]: `io.helidon.config.encryption.MpEncryptionFilter` is a public class and is now moved to `io.helidon.config.mp.MpEncryptionFilter`.

This is not backward compatible, we should make sure this is documented.

Comment (tomas-langer) [reply config/config-mp/src/main/java/io/helidon/config/mp/MpEncryptionFilter.java:17]: is release notes sufficient? Or should I change something in the sources?

Comment (tomas-langer) [reply config/config-mp/src/main/java/io/helidon/config/mp/MpEncryptionFilter.java:17]: Updated the PR - keeping the old class in with no body, and explanation and pointer.

Comment (romain-grecourt) [reply config/config-mp/src/main/java/io/helidon/config/mp/MpEncryptionFilter.java:17]: If the class does not implement `MpConfigFilter`, it's still incompatible.

The first iteration of the PR was fine, if we are okay we introducing a backward incompatibility in a dot-dot release.

Otherwise, we have to have config-encryption depend on config-mp. (I.e `require io.helidon.config.mp` and non optional dependency).

Comment (tomas-langer) [reply config/config-mp/src/main/java/io/helidon/config/mp/MpEncryptionFilter.java:17]: That brings in the MP Config API dependency, which is unfortunate in a Helidon SE application. 

The only possible issue is if somebody explicitly uses this class. 
Filters are ONLY loaded using ServiceLoader - i.e. there is no API where you can register such a filter. 
As the class is final, users should never have a reference to it in their code.

I think this makes our decision a bit easier and we should introduce this (slightly) backward incompatibility to fix a dependency tree issue.

**Review by romain-grecourt — APPROVED** [review]
