### PR TITLE
4.x: Meta-configuration fixes

### LINKED ISSUE #9218: MetaConfig is used implicitly when nothing is configured
## Environment Details
* Helidon Version: 4.1.0
* Helidon SE

----------

This issue is filed against 4.1.0, however the same can be observed with 3.2.8 and 2.6.7.

## Problem Description

When there are no config sources, meta config is used which leads to bad behaviors.

See https://github.com/helidon-io/helidon/blob/90274ad4359a74e61f685ddefd37f404398c74c7/config/config/src/main/java/io/helidon/config/BuilderImpl.java#L433

---

The javadoc of `Config.just` states:
> Creates a new Config loaded from the specified ConfigSources. No other sources will be included.

We'd expect `Config.just()` to create an empty instance.
However if there a file called `config-profile.yaml` or `meta-config.yaml` in the current directory it will be picked up.

This also occurs with code that is effectively similar to `Config.just`:

```java
Config.builder()
    .disableSystemPropertiesSource()
    .disableEnvironmentVariablesSource()
    .build();
```

---

When using Helidon MP with `-Dio.helidon.config.mp.meta-config=config-profile.yaml`, any code that builds an effectively empty SE config instance will load the file, however MP meta config and SE meta config are not compatible so this is guaranteed to fail.

E.g.
If there is no property prefixed with `metrics.` and `mp.metrics.` in the configuration, then `MetricsCdiExtension` will build a config instance with no config sources.

 https://github.com/helidon-io/helidon/blob/5bd8681d69278e910645dd71f32e6a021647cd80/microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java#L449

```
Exception in thread "main" java.lang.IllegalArgumentException: Config source of type properties is not supported. Supported types: [file, prefixed, classpath, system-properties, directory, inlined, url, environment-variables]
	at io.helidon.config.MetaProviders.lambda$configSource$7(MetaProviders.java:116)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config.MetaProviders.configSource(MetaProviders.java:116)
	at io.helidon.config.MetaConfig.configSource(MetaConfig.java:201)
	at io.helidon.config.MetaConfig.lambda$configSources$1(MetaConfig.java:239)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.helidon.config.MetaConfig.lambda$configSources$2(MetaConfig.java:239)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.common.mapper.OptionalValue.ifPresent(OptionalValue.java:188)
	at io.helidon.config.MetaConfig.configSources(MetaConfig.java:239)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.helidon.config.MetaConfig.configSources(MetaConfig.java:249)
	at io.helidon.config.BuilderImpl.buildConfigSources(BuilderImpl.java:434)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:334)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:53)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.componentConfig(MetricsCdiExtension.java:458)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.configure(MetricsCdiExtension.java:551)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.registerService(MetricsCdiExtension.java:321)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:126)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:311)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:258)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
	at io.helidon.microprofile.cdi.CdiStartupProvider.start(CdiStartupProvider.java:39)
	at io.helidon.Main.main(Main.java:85)
```

## Steps to reproduce

```java
class ConfigEmptyTest {

    @Test
    void testJustEmpty() {
        Config config = Config.just();
        assertThat(config.get("foo").asString().orElse("bar"), is("bar"));
    }
    
    @Test
    void testDisableBuiltInSources() {
        Config config = Config.builder()
                .disableSystemPropertiesSource()
                .disableEnvironmentVariablesSource()
                .build();
        assertThat(config.get("foo").asString().orElse("bar"), is("bar"));
    }
}
```

src/test/resources/meta-config.yaml:

```yaml
sources:
  - type: "inlined"
    properties:
      foo: "not-bar"
```

### LINKED ISSUE #9220: 4.x - GlobalConfig.config() should be configured when using Helidon MP
## Environment Details
* Helidon Version: 4.1.0
* Helidon MP

----------

## Problem Description

If not configured, `GlobalConfig` initializes a default config using `Config.create()` via `io.helidon.config.HelidonConfigProvider`.

`Config.create()` loads meta-config by default, if there a file called `config-profile.yaml` or `meta-config.yaml` in the current directory it will be picked up.

However MP meta config and SE meta config are not compatible so this is guaranteed to fail.

```
2024.08.28 17:09:40 INFO io.helidon.config.MetaConfigFinder Thread[#1,main,5,main]: Found meta configuration file: /private/tmp/quickstart-mp/meta-config.yaml
Exception in thread "main" java.lang.IllegalArgumentException: Config source of type properties is not supported. Supported types: [file, prefixed, classpath, system-properties, directory, inlined, url, environment-variables]
	at io.helidon.config.MetaProviders.lambda$configSource$7(MetaProviders.java:116)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config.MetaProviders.configSource(MetaProviders.java:116)
	at io.helidon.config.MetaConfig.configSource(MetaConfig.java:201)
	at io.helidon.config.BuilderImpl.lambda$config$3(BuilderImpl.java:378)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.helidon.config.BuilderImpl.lambda$config$4(BuilderImpl.java:378)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.common.mapper.OptionalValue.ifPresent(OptionalValue.java:188)
	at io.helidon.config.BuilderImpl.config(BuilderImpl.java:378)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.config.Config$Builder.metaConfig(Config.java:1639)
	at io.helidon.config.Config.create(Config.java:321)
	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118)
	at io.helidon.config.HelidonConfigProvider.create(HelidonConfigProvider.java:40)
	at io.helidon.common.config.GlobalConfig.lambda$static$0(GlobalConfig.java:49)
	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118)
	at io.helidon.common.config.GlobalConfig.config(GlobalConfig.java:73)
	at io.helidon.metrics.api.MetricsConfigSupport$BuilderDecorator.decorate(MetricsConfigSupport.java:85)
	at io.helidon.metrics.api.MetricsConfig$BuilderBase.preBuildPrototype(MetricsConfig.java:602)
	at io.helidon.metrics.api.MetricsConfig$Builder.buildPrototype(MetricsConfig.java:809)
	at io.helidon.metrics.api.MetricsConfig.create(MetricsConfig.java:86)
	at io.helidon.webserver.observe.metrics.MetricsObserverConfig$BuilderBase.<init>(MetricsObserverConfig.java:88)
	at io.helidon.webserver.observe.metrics.MetricsObserverConfig$Builder.<init>(MetricsObserverConfig.java:422)
	at io.helidon.webserver.observe.metrics.MetricsObserverConfig.builder(MetricsObserverConfig.java:46)
	at io.helidon.webserver.observe.metrics.MetricsObserver.builder(MetricsObserver.java:71)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.configure(MetricsCdiExtension.java:553)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.registerService(MetricsCdiExtension.java:321)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:126)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:311)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:258)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
	at io.helidon.microprofile.cdi.CdiStartupProvider.start(CdiStartupProvider.java:39)
	at io.helidon.Main.main(Main.java:85)
```

---

Instead it should be configured with the MicroProfile config wrapped as a Helidon Config.

I.e.
```java
MpConfig.toHelidonConfig(ConfigProvider.getConfig());
```

## Steps to reproduce

```shell
# generate project
helidon init --version 4.1.0 --batch -Dflavor=mp -DappType=quickstart

# build
cd quickstart-mp
mvn clean install -DskipTests

# generate a MP meta-config file named meta-config.yaml
cat <<EOF > meta-config.yaml                                         
add-default-sources: true
sources:
  - type: "properties"
    optional: true
    path: "foo.properties"
EOF

# start the app with the meta config
java -Dio.helidon.config.mp.meta-config=meta-config.yaml -jar target/quickstart-mp.jar
```

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #9218 
Resolves #9220 

- make sure meta-configuration failures do not fail creation of config (such as when accidentally naming MP meta-config just `meta-config.yaml` and then SE picking it up
- set GlobalConfig from MP Config provider resolver
- do not use SE meta configuration unless explicitly requested (only in `Config.create()` and `Config.builder().metaConfig()`)

Added tests.

### CODE REVIEW

File: config/config/src/main/java/io/helidon/config/BuilderImpl.java [hunk 1]
```diff
@@ -427,14 +430,13 @@ private ConfigSourcesRuntime buildConfigSources(ConfigContextImpl context) {
...
         }
 
-        boolean nothingConfigured = sources.isEmpty();
+        boolean nothingConfigured = sources.isEmpty() && !sourcesConfigured;
 
         if (nothingConfigured) {
             // use meta configuration to load all sources
-            MetaConfig.configSources(mediaType -> context.findParser(mediaType).isPresent(), context.supportedSuffixes())
-                    .stream()
+            MetaConfigFinder.findConfigSource(mediaType -> context.findParser(mediaType).isPresent(), context.supportedSuffixes())
```
Comment (romain-grecourt) [inline config/config/src/main/java/io/helidon/config/BuilderImpl.java:437]: Should this also catch & log the exception similar to `Config.Builder.metaConfig()` ?

Comment (tomas-langer) [reply config/config/src/main/java/io/helidon/config/BuilderImpl.java:437]: This is not using meta-configuration. It only looks for default config sources (such as `application.yaml`), so it should not throw that exception at all.

Comment (romain-grecourt) [reply config/config/src/main/java/io/helidon/config/BuilderImpl.java:437]: If I execute this code with a bad `meta-config.yaml` in the current working directory, it throws an exception:

```java
MetaConfig.configSources(mediaType -> true, List.of("yaml"))
        .stream()
        .count();
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Config source of type properties is not supported. Supported types: [file, prefixed, classpath, system-properties, directory, inlined, url, environment-variables]
	at io.helidon.config/io.helidon.config.MetaProviders.lambda$configSource$7(MetaProviders.java:116)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config/io.helidon.config.MetaProviders.configSource(MetaProviders.java:116)
	at io.helidon.config/io.helidon.config.MetaConfig.configSource(MetaConfig.java:201)
	at io.helidon.config/io.helidon.config.MetaConfig.lambda$configSources$1(MetaConfig.java:239)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.helidon.config/io.helidon.config.MetaConfig.lambda$configSources$2(MetaConfig.java:239)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.common.mapper/io.helidon.common.mapper.OptionalValue.ifPresent(OptionalValue.java:188)
	at io.helidon.config/io.helidon.config.MetaConfig.configSources(MetaConfig.java:239)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.helidon.config/io.helidon.config.MetaConfig.configSources(MetaConfig.java:249)
```

Comment (tomas-langer) [reply config/config/src/main/java/io/helidon/config/BuilderImpl.java:437]: will check

Comment (romain-grecourt) [reply config/config/src/main/java/io/helidon/config/BuilderImpl.java:437]: The code I shared above uses `MetaConfig.configSources` whereas this PR changes to ` MetaConfigFinder.findConfigSource` ; so my comment is not relevant.

**Review by romain-grecourt — APPROVED** [review]

**Review by danielkec — APPROVED** [review]
