### PR TITLE
3.x: Fix empty config values propagation (#9888)

### LINKED ISSUE #9888: 3.x: MpConfigSources.create does not handle empty values
Backport of https://github.com/helidon-io/helidon/issues/9506 for 3.x

### PR DESCRIPTION
**Pull request by Captain1653**
### Description
Fixes #9888 

The same [was done for 4.x](https://github.com/helidon-io/helidon/issues/9506)

### CODE REVIEW

File: microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/connector/ConnectorConfigTest.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+import org.junit.jupiter.api.Disabled;
+import org.junit.jupiter.api.Test;
+
+import java.util.Map;
+import java.util.concurrent.ExecutionException;
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+
+@Disabled("because @Inject and @HelidonTest(resetPerTest=true) throws exception")
```
Comment (Captain1653) [inline microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/connector/ConnectorConfigTest.java:46]: This is a little hard  for me :) . Let me explain.

The same tests were added for 4.x and it works there, but for 3.x I have this exception
Screenshot 2025-03-12 at 09 46 34

The error message is clear. I can't inject, because of this parameter `resetPerTest=true`. It works for 4.x after [this refactoring](https://github.com/helidon-io/helidon/commit/1baabd5042389661b75238c774c38aceb132bd6b#diff-5dea65dfdf039d5e5a05021730d568db7512b0734e5580b1cc2239432b766267L156) .

But how can I fix this test for 3.x? Or should I remove these tests at all, because `AdHocConfigBuilderTest` does all necessary checks?

Comment (romain-grecourt) [reply microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/connector/ConnectorConfigTest.java:46]: The test class only has one method so you don't need to use `resetPerTest = true`.
You can move the `@AddConfig` and `@AddBean` annotations on the class.

Comment (Captain1653) [reply microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/connector/ConnectorConfigTest.java]: Thank you

**Review by romain-grecourt — APPROVED** [review]
