### PR TITLE
Connection cache 100 continue

### LINKED ISSUE #9736: 4.x: WebClient.readContinueTimeout does not work with cached connections
## Environment Details
* Helidon Version: 4.x
* Helidon SE

----------

## Problem Description

The idle thread starts the read before `SO_TIMEOUT` is set to the [continue timeout](https://github.com/helidon-io/helidon/blob/dec95f3c6d40de9da339b192413eda069fa9c9b0/webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallOutputStreamChain.java#L393).
Thus, the timeout for the `100 Continue` response is the read timeout (defaults to 30 seconds).

I.e. If the server does not handle `Expect: 100-continue`, the request takes a long time on cached connections.

---

The client logic that [handles](https://github.com/helidon-io/helidon/blob/dec95f3c6d40de9da339b192413eda069fa9c9b0/webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallOutputStreamChain.java#L399) socket read timeout does not work with cached connections.
The idle task completion [wraps](https://github.com/helidon-io/helidon/blob/dec95f3c6d40de9da339b192413eda069fa9c9b0/common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java#L126) all exceptions with a RuntimeException which bubbles up and closes the connection.

I.e. If the server does not handle `Expect: 100-continue`, every other request takes a very long time.
The 2nd request times-out on the read timeout, and then fail.

---

I did some experimentation to "cancel" the idle thread.

It does seem to fix the use-case of a server with bad support for `Expect: 100-continue`.

```java
private void handle() {
    while (!canceled) {
        try {
            socket.setSoTimeout(500);
            next = upstream.read();
            if (next <= 0) {
                closed = true;
            }
            // restore SO_TIMEOUT
            socket.setSoTimeout((int) readTimeout.toMillis());
            return;
        } catch(SocketTimeoutException ignored) {
        } catch (IOException e) {
            closed = true;
            throw new UncheckedIOException(e);
        }
    }
}
```

## Steps to reproduce

See #9731

### PR DESCRIPTION
**Pull request by Verdent**
### Description

Fixes #9736
Fixes https://github.com/helidon-io/helidon/issues/9731

This issue introduces a new way of idle connection handling. It splits the desired idle timeout and uses small 500 ms timeouts until the overall desired timeout is reached. This helps to interrupt the idle timeout mechanism.

FYI: I will add some more comments to the code

### Documentation

None

### CODE REVIEW

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java [hunk 1]
```diff
@@ -36,14 +40,23 @@
...
     private volatile boolean closed = false;
+    private volatile boolean cancelled = false;
     private Future<?> idlingThread;
 
-    IdleInputStream(InputStream upstream, String childSocketId, String socketId) {
+    IdleInputStream(Socket socket, InputStream upstream, String childSocketId, String socketId, Duration idleTimout) {
+        this.socket = socket;
         this.upstream = upstream;
+        this.idleTimeoutIterations = (int) (idleTimout.toMillis() / TIMEOUT);
+        this.lastIterationRemainder = (int) (idleTimout.toMillis() % TIMEOUT);
```
Comment (spericas) [inline common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:59]: After looking at the final version of this, I think there's no need for the "remainder" logic TBH. Timeouts are approximations (especially at the socket layer), so it should be enough to divide by TIMEOUT or maybe add 1 to that. No need for finer control than that. That should simplify your logic a bit, making it easier to read.

Comment (romain-grecourt) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:59]: +1 the loop should just increment the max iterations

Comment (romain-grecourt) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:59]: Something like this maybe ?

```java
try {
    int timeout = socket.getSoTimeout();
    for (int i = 0; i < maxIterations && !cancelled; i++) {
        try {
            int t = socket.getSoTimeout();
            if (t != 500) {
                timeout = t;
            }
            socket.setSoTimeout(500);
            next = upstream.read();
            if (next <= 0) {
                closed = true;
            }
            break;
        } catch (SocketTimeoutException ignored) {
        }
    }
    socket.setSoTimeout(timeout);
} catch (IOException e) {
    closed = true;
    throw new UncheckedIOException(e);
}
```

Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java]: Alright, I have simplified the logic.

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java [hunk 2]
```diff
@@ -107,20 +122,46 @@ boolean isClosed() {
...
     private void handle() {
         try {
-            next = upstream.read();
-            if (next <= 0) {
-                closed = true;
+            //Currently configured socket read timeout. This is intended to be restored after this method finishes
+            int toRestore = -1;
+            for (int i = 0; !cancelled; i++) {
+                try {
+                    toRestore = timeoutToRestore(toRestore);
```
Comment (romain-grecourt) [inline common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:129]: No need for a method, having the if statement here makes it more readable.

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java [hunk 3]
```diff
@@ -107,20 +122,46 @@ boolean isClosed() {
...
+                    socket.setSoTimeout(TIMEOUT);
+                    next = upstream.read();
+                    if (next <= 0) {
+                        closed = true;
+                        return;
+                    }
+                    break;
+                } catch (SocketTimeoutException e) {
+                    if (i + 1 >= idleTimeoutIterations) {
```
Comment (romain-grecourt) [inline common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:138]: Do we need to throw the last socket timeout ?
Ins't it better to ignore it them and let the consuming code do another read ?

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java [hunk 4]
```diff
@@ -36,14 +40,25 @@
  */
 class IdleInputStream extends InputStream {
 
+    /**
+     * This needs to cooperate with 100-continue timeout.
+     * Some low number is needed here for a quick iterations.
+     */
+    private static final int TIMEOUT = 100;
```
Comment (romain-grecourt) [inline common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:47]: Should it be configurable ?

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 3 above)
Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:137]: I am trying to have the same functionality as we had before and we were throwing the exception there.

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 2 above)
Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:128]: Hm... I see this as a cleaner option :-)

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 4 above)
Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:47]: I think it does not necessarily need to be. Or do you?

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 2 above)
Comment (romain-grecourt) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:127]: How is this better, it's 3 lines of code, it's used only once and does not mutate any state.

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 4 above)
Comment (romain-grecourt) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:46]: The value was 500, it's now 100 and it's a value we picked somewhat arbitrarily.
So why not make it configureable from the start.

Comment (tomas-langer) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:46]: The 100 was chosen on my request. We need to have a reasonable small time, yet something that will not burn too much CPU.
The default timeout for 100 continue is 1 second, so we expect to spend max. 1.1 second waiting for it. Each higher number means more "error" introduced.

Of course if somebody sets a really small timeout for 100 continue, they would get up to 100 millis added on the first request (further request will skip 100 continue). I think this is a reasonable behavior for now.

Also configuration is not available in sockets, and this would cause a ripple effect in all APIs that use them. If we need to add configurability, we  would also need to add an object to send it around.

**Review by tomas-langer — DISMISSED** [review]

**Review by tomas-langer — DISMISSED** [review]

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 2 above)
Comment (spericas) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:132]: I agree with Romain, that should be inlined. Also assigning to a param is generally frowned upon.

File: webclient/api/src/main/java/io/helidon/webclient/api/ClientConnection.java [hunk 5]
```diff
@@ -61,4 +61,18 @@ public interface ClientConnection extends ReleasableResource {
      * @param readTimeout connection read timeout
      */
     void readTimeout(Duration readTimeout);
+
+    /**
+     * Check whether this connection is allowed to send 100-Continue.
+     *
+     * @return whether 100-Continue is allowed
+     */
+    boolean allowExpectContinue();
```
Comment (romain-grecourt) [inline webclient/api/src/main/java/io/helidon/webclient/api/ClientConnection.java:70]: I very much dislike the http specific method on the connection interface, although I understand its purpose.
This could be abstracted away as state with a word (E.g a long) and some mask constant.

Also since this is going to be truly implemented in only one implementation, we should probably use default method. These are public interfaces after all so that would preserve backward compatibility.

File: common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java (hunk 2 above)
Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:132]: You mean to use ternary operator? What is so bothering you guys in having this method?

Yeah, that parameter assignment was a mistake. I did not realize it is a parameter. It is fixed in the latest PR already.

Comment (romain-grecourt) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:132]: Because it's just one if statement with an assignment, that shouldn't be in a method.

```java
int t = socket.getSoTimeout();
if (t != ITERATION_TIME_MILLIS) {
    toRestore = t;
}
```

Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:132]: If this method bothers you so much, I will remove it.

Comment (Verdent) [reply common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java:132]: Alright, I will remove it, if it helps to get this merged.

**Review by tomas-langer — APPROVED** [review]

**Review by tomas-langer — APPROVED** [review]

**Review by romain-grecourt — APPROVED** [review]
