### PR TITLE
4.x: Concurrency limits module, and support in Helidon WebServer

### LINKED ISSUE #8897: Provide adaptive concurrency limits
# Why

There may be several reasons why adaptive concurrency limiting is preferred over using a fixed limit:

1. **Dynamic System Conditions**: In a distributed system, conditions such as load, resource availability, and topology can change frequently due to factors like auto-scaling, partial outages, code deployments, or fluctuations in traffic patterns. A fixed concurrency limit cannot adapt to these dynamic conditions, leading to either under-utilization of resources or overwhelmed services.

2. **Latency Sensitivity**: Different services or use cases may have varying sensitivity to latency. A fixed concurrency limit cannot account for these differences, potentially leading to either excessive queuing and high latency or under-utilization of resources. An adaptive approach can adjust the limit based on observed latencies, maintaining desired performance characteristics.

3. **Simplicity and Autonomy**: Manually determining and configuring fixed concurrency limits for every service or instance can be a complex and error-prone process, especially in large-scale distributed systems. An adaptive approach can autonomously and continuously adjust the limit without manual intervention, simplifying operations and reducing the risk of misconfiguration.

4. **Resilience and Self-Healing**: By automatically adjusting the concurrency limit based on observed conditions, an adaptive approach promotes resilience and self-healing capabilities. It allows services to shed excessive load during periods of high demand or resource constraints, preventing cascading failures and promoting graceful degradation.

While a fixed concurrency limit may be easier to reason about and configure initially, it lacks the flexibility and adaptability required in modern, dynamic distributed systems. An adaptive approach provides the ability to continuously optimize performance, resource utilization, and resilience in the face of changing conditions, ultimately leading to a more robust and efficient system.

# Suggestion

Ideally, a user would be able to describe the limiting algorithm in the [ListenerConfig](https://helidon.io/docs/v4/apidocs/io.helidon.webserver/io/helidon/webserver/ListenerConfig.html#maxConcurrentRequests()) that fit their needs instead of a fixed number for `maxConcurrentRequests`. The `Limit` and `Limiter` interfaces from [Netflix's concurrency limits library](https://github.com/Netflix/concurrency-limits/blob/main/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/Limit.java#L24) are a good starting point. In the first iteration we should provide the following implementations
- no limit,
- fixed limit,
- AMID limit.

Instead of passing a `Semaphore` for requests in the `ServerListener` to the `ConnectionHandler` we would pass a `Limiter` implementation that holds the configured `Limit` algorithm. The `Limiter` would be used instead if the `Semaphore` to acquire a token per request. If no token can be acquired the limit is exceeded and the request can be rejected.

While implementing a Proof of Concept (PoC), I asked myself where do we want to place the Limiting API. I guess, we need a new submodule `concurrency-limits` which holds `Limit` and `Limiter` interfaces and a standard set of implementations. The `webserver` module then depends on `concurrency-limits`.

Another question is, how do we want to make the various limiting algorithm configurable. Today, we have just the single property `maxConcurrentRequests`, but in future we want to choose from a set of different implementations, e.g. no limit, fixed limit, AMID limit, Vegas limit etc.

When testing the PoC, I noticed that when the access log feature is activated, rejected requests are not logged in the access log file. Is this behavior intentional or is this a bug?

Additionally, extending the metrics (looking at `KeyPerformanceIndicatorMetricsImpls`) would be helpful, to be able to observe how a service is doing. I'm thinking here about the following request limiting metrics:
- success counter
- ignored counter
- rejected counter

### LINKED ISSUE #9229: Provide configurable option to queue requests when concurrency is limited with  "max-concurrent-requests"
## Environment Details
* Helidon Version:  4.x 
* Helidon SE or Helidon MP. : SE & MP 
* JDK version:  Java 21 
* OS:  Linux 
* Docker version (if applicable):

In. Helidon 4.x  with. Webserver that supports loom based virtual threads ,  uses the  new thread per request model .  So by design there is no longer  server thread pool  or  any associated  queues where requests get queued .   

By default. there is no limit on concurrency  and this can lead to issues  when resources such as DB connections,  external system integrations,  and. other such downstream resources  are limited.   This can lead to  performance degrade and also errors when requests timeout  waiting for such resources.  

To address this  Helidon  provides  the  "max-concurrent-requests" parameter on the Listener configuration.    While it helps to  limit the concurrency , the  services are running into issues when trying to use this  parameter to limit the concurrency 

 When the "max-concurrent-requests" parameter is set,  any  surge requests beyond the  limit get rejected and fail with 503.  There can be occasional surges that can cause the concurrency to go beyond the  configured limit, and such cases teh requests would error out. 
This behaviour   is  not consistent with  the behavior in earlier versions of Helidon where under this situation the requests would get queued in the queue associated with Helidon's server thread pool. 

It would be  good have an additional configurable options  in  Helidon 4 , where. one can  additionally enable queueing of requests ,  when   a limit is configured for max-concurrent-requests" 
Something like below

server :  
  max-concurrent-requests : 40 
  request-queue : 
     enable :  true 
     max :  100

### PR DESCRIPTION
**Pull request by tomas-langer**
### Description
Resolves #8897
Resolves #9229

### Documentation
This PR introduces 
- a new module `common/concurrency/limits` that provides API and SPI for concurrency limit implementations, and a couple of default implementations (AIMD, Fixed).
- a new module `webserver/concurrency-limits` that provides feature with a filter to impose limits within a filter in routing
- update of `webserver/webserver` to use a `Limit` instead of a `Semaphore` in connection handlers (backward compatible)

Configuration reference will be in the generated documentation.

#### Configure limits on WebServer
This will configure limit for a server listener (configurable per listener), enforced on the connection level (i.e. outside of routing and filters).

The default behavior is the same (unlimited).
If `server.max-concurrent-requests` is configured (value is not `-1`), it will be used and `concurrency-limit` configuration for the listener will be ignored.

Configuration:
```yaml
server:
  port: 8080
  concurrency-limit:
    aimd: # `limit type`
      # AIMD limit configuration
```
#### Configure limits for routing
This will configure limit for as a server feature, enforced in an HTTP filter.
Configuration:
```yaml
server:
  features:
    limits: # the feature is called `limits`
      enabled: true
      concurrency-limit: # `limit` configuration of the `limits` server feature
        fixed: # `limit type`
          permits: 1
          queue-length: 10
```

### CODE REVIEW

**Review by arouel — APPROVED** [review]
LGTM, great rework and integration

**Comment by vasanth-bhat** [comment]
Have few clarifications

1.  Going through    Readme  , there is mention about 'Semaphore' concurrency limit type in  addition to aimd & BulkHead.  Is this same as. "basic" (BasicLimit)?   Also how is this different from specifying.  "server.max-concurrent-requests"? 

2.  For the  BulkHead,   it would be good to have metrics support ,   around  queueing ,  for example  %  queue full.  This is important in production to monitor  the queueing.  

3.  For AMID , it would be good to ahem a metrics around the dynamic concurrency limit in use. A Histogram may be useful here.

**Comment by tomas-langer** [comment]
After discussing the needs in Helidon, we must do this using the `permit` approach, so this can be reused in webclient. 
I will refactor the PR.

**Comment by arouel** [comment]
I wanted to bring up that metrics would be super important for production as @vasanth-bhat brought it up as well. Within my draft I figured quickly that the limiting works as expected but metrics would give me the insights I need to build convidence. Maybe this is something for a follow-up Pull Request, idk.

**Comment by tomas-langer** [comment]
Metrics must be a follow up, as it would require much more work. I cannot just add a dependency on `helidon-metrics-api`, as it would introduce it everywhere (maybe that is the solution, but it requires a bit more thought).
I will finish this PR as the introduction of concurrency limits. We can look into the metrics as a follow up (this would make sense for fault tolerance as well, not just concurrency limits).

**Comment by tomas-langer** [comment]
Pushed a new version, updated original description to reflect new implementation.
I have implemented the `fixed` limit as a more general feature - it supports queing now, so we no longer need fault tolerance for this.
How to add this to metrics needs to be a follow up.

**Comment by tomas-langer** [comment]
Created a follow up issue: https://github.com/helidon-io/helidon/issues/9304

**Comment by vasanth-bhat** [comment]
Went through the new changes.  

  I think it would help to clarify between  the below 2 , with example to understand  the difference between the two.   Do  both them provide same functionality but via different approaches ?

1. Fixed Limit with queueing support at the connection level  (or a server listener )
2. Fixed limit with queueing as server feature enforced via filter.

File: common/concurrency/limits/src/main/java/io/helidon/common/concurrency/limits/FixedLimit.java [hunk 1]
```diff
@@ -0,0 +1,348 @@
...
+    /**
+     * Timeout of a request that is enqueued.
+     */
+    public static final String DEFAULT_QUEUE_TIMEOUT_DURATION = "PT1S";
+
+    static final String TYPE = "fixed";
+
+    private final FixedLimitConfig config;
+    private final LimiterHandler handler;
+    private int initialPermits;
```
Comment (danielkec) [inline common/concurrency/limits/src/main/java/io/helidon/common/concurrency/limits/FixedLimit.java:55]: Can be final?

File: webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java [hunk 2]
```diff
@@ -516,15 +516,35 @@ private void handle() {
...
                     ctx.log(LOGGER, TRACE, "Too many concurrent requests, rejecting request.");
                     response.status(Status.SERVICE_UNAVAILABLE_503)
                             .send("Too Many Concurrent Requests");
                     response.commit();
+                } else {
+                    LimitAlgorithm.Token permit = token.get();
+                    try {
+                        routing.route(ctx, request, response);
+                    } finally {
+                        if (response.status() == Status.NOT_FOUND_404) {
```
Comment (arouel) [inline webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java:533]: Should we allow a user to specify which 4xx codes can be ignored?

File: webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java [hunk 3]
```diff
@@ -183,30 +187,35 @@ public void handle(Semaphore requestSemaphore) throws InterruptedException {
...
+                } else {
+                    LimitAlgorithm.Token permit = token.get();
 
+                    try {
+                        this.lastRequestTimestamp = DateTime.timestamp();
+                        route(prologue, headers);
+                        permit.success();
+                        this.lastRequestTimestamp = DateTime.timestamp();
+                    } catch (Throwable e) {
+                        permit.dropped();
```
Comment (arouel) [inline webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java:215]: Maybe something for a future PR: Should we allow a user to specify which exception can be recorded as ignored instead of being counted as dropped?

**Review by arouel — APPROVED** [review]

File: common/concurrency/limits/src/main/java/io/helidon/common/concurrency/limits/AimdLimitImpl.java [hunk 4]
```diff
@@ -0,0 +1,193 @@
...
+        }
+        if (maxLimit < minLimit) {
+            throw new ConfigException("Max limit must be higher than min limit");
+        }
+        if (initialLimit > maxLimit) {
+            throw new ConfigException("Initial limit must be lower than max limit");
+        }
+        if (initialLimit < minLimit) {
+            throw new ConfigException("Initial limit must be higher than minimum limit");
+        }
```
[the remark this answers is not in the document]
Comment (tomas-langer) [reply common/concurrency/limits/src/main/java/io/helidon/common/concurrency/limits/AimdLimitImpl.java:67]: ah, the messages are wrong, I see

**Review by danielkec — APPROVED** [review]

**Review by Verdent — APPROVED** [review]
