### PR TITLE
Windows Github Action

### LINKED ISSUE #6714: Helidon 4.x cannot be built on Windows
After merging Pico, it is not possible to build Helidon on Windows.

```
dub 27, 2023 4:05:54 ODP. io.helidon.pico.tools.AbstractFilerMessager error
SEVERE: Failed to write resource file: Invalid relative name: META-INF\services\io.helidon.pico.api.ModuleComponent
io.helidon.pico.tools.ToolsException: Failed to write resource file: Invalid relative name: META-INF\services\io.helidon.pico.api.ModuleComponent
        at io.helidon.pico.tools.CodeGenFiler.codegenResourceFilerOut(CodeGenFiler.java:286)
        at io.helidon.pico.tools.CodeGenFiler.codegenMetaInfServices(CodeGenFiler.java:194)
        at io.helidon.pico.tools.DefaultActivatorCreator.codegenMetaInfServices(DefaultActivatorCreator.java:300)
        at io.helidon.pico.tools.DefaultActivatorCreator.codegen(DefaultActivatorCreator.java:202)
        at io.helidon.pico.tools.DefaultActivatorCreator.createModuleActivators(DefaultActivatorCreator.java:124)
        at io.helidon.pico.processor.BaseAnnotationProcessor.doFiler(BaseAnnotationProcessor.java:632)
        at io.helidon.pico.processor.BaseAnnotationProcessor.process(BaseAnnotationProcessor.java:189)
        at io.helidon.pico.processor.ServiceAnnotationProcessor.process(ServiceAnnotationProcessor.java:108)
        at io.helidon.pico.configdriven.processor.ConfiguredByProcessor.process(ConfiguredByProcessor.java:92)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1018)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:854)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1260)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1399)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1248)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:930)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:82)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:694)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcessWithProperClassloader(JavacCompiler.java:675)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:664)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:186)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1209)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:198)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalArgumentException: Invalid relative name: META-INF\services\io.helidon.pico.api.ModuleComponent
        at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForOutput(JavacFileManager.java:894)
        at java.compiler@20/javax.tools.JavaFileManager.getFileForOutputForOriginatingFiles(JavaFileManager.java:533)
        at jdk.compiler/com.sun.tools.javac.main.DelegatingJavaFileManager.getFileForOutputForOriginatingFiles(DelegatingJavaFileManager.java:139)
        at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createResource(JavacFiler.java:551)
        at io.helidon.pico.tools.AbstractFilerMessager.createResource(AbstractFilerMessager.java:121)
        at io.helidon.pico.tools.CodeGenFiler.codegenResourceFilerOut(CodeGenFiler.java:256)
        ... 50 more

dub 27, 2023 4:05:54 ODP. io.helidon.pico.processor.BaseAnnotationProcessor error
SEVERE: ConfiguredByProcessor: Error: Error detected while processing [io.helidon.nima.webserver.LoomServer]
io.helidon.pico.tools.ToolsException: Error detected while processing [io.helidon.nima.webserver.LoomServer]
        at io.helidon.pico.processor.BaseAnnotationProcessor.doFiler(BaseAnnotationProcessor.java:645)
        at io.helidon.pico.processor.BaseAnnotationProcessor.process(BaseAnnotationProcessor.java:189)
        at io.helidon.pico.processor.ServiceAnnotationProcessor.process(ServiceAnnotationProcessor.java:108)
        at io.helidon.pico.configdriven.processor.ConfiguredByProcessor.process(ConfiguredByProcessor.java:92)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1018)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:854)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1260)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1399)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1248)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:930)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:82)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:694)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcessWithProperClassloader(JavacCompiler.java:675)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:664)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:186)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1209)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:198)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: io.helidon.pico.tools.ToolsException: error during codegen
        at io.helidon.pico.processor.BaseAnnotationProcessor.doFiler(BaseAnnotationProcessor.java:634)
        ... 45 more
Caused by: io.helidon.pico.tools.ToolsException: Failed in create
        at io.helidon.pico.tools.DefaultActivatorCreator.createModuleActivators(DefaultActivatorCreator.java:130)
        at io.helidon.pico.processor.BaseAnnotationProcessor.doFiler(BaseAnnotationProcessor.java:632)
        ... 45 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
        at io.helidon.pico.tools.CodeGenFiler.codegenResourceFilerOut(CodeGenFiler.java:290)
        at io.helidon.pico.tools.CodeGenFiler.codegenMetaInfServices(CodeGenFiler.java:194)
        at io.helidon.pico.tools.DefaultActivatorCreator.codegenMetaInfServices(DefaultActivatorCreator.java:300)
        at io.helidon.pico.tools.DefaultActivatorCreator.codegen(DefaultActivatorCreator.java:202)
        at io.helidon.pico.tools.DefaultActivatorCreator.createModuleActivators(DefaultActivatorCreator.java:124)
        ... 46 more

```

### LINKED ISSUE #6717: Add Windows build to PR validation workflow

### PR DESCRIPTION
**Pull request by tvallin**
### Description

Fixes #6717
Fixes #6714

### Documentation

Run unit tests and packaging (jar, jlink and native-image) on windows.

Performance before changes (main):  24m 38s
Performance after changes: 27m 16s

### CODE REVIEW

File: common/common/src/main/java/io/helidon/common/Strings.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        return value.replaceAll("\r\n", "\n");
+    }
+
+    /**
+     * Force UNIX style path on Windows.
+     *
+     * @param value The value to normalize, may be {@code null}
+     * @return normalized value
+     */
+    public static String normalizePath(String value) {
```
Comment (trentjeff) [inline common/common/src/main/java/io/helidon/common/Strings.java:42]: taking `CharSequence` typed arg here and above would be more flexible.

File: integrations/oci/sdk/pom.xml [hunk 2]
```diff
@@ -35,7 +35,20 @@
...
         <module>runtime</module>
-        <module>tests</module>
     </modules>
 
+    <profiles>
+        <profile>
+            <id>run-test</id>
+            <activation>
+                <os>
+                    <family>!Windows</family>
```
Comment (trentjeff) [inline integrations/oci/sdk/pom.xml:45]: why??  We should reference an issue here or add comments around it.

File: nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/Http2ErrorHandlingWithOutputStreamTest.java [hunk 3]
```diff
@@ -172,6 +174,7 @@ void testGetOutputStreamWriteTwiceThenError_expect_invalidResponse() {
     }
 
     @Test
+    @DisabledOnOs(OS.WINDOWS)
```
Comment (trentjeff) [inline nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/Http2ErrorHandlingWithOutputStreamTest.java:177]: why?  Can't we fix the core issue in this PR?  If not we need to add more comments w/ a tracking issue.

File: nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/tests/integration/client/HttpProxyTest.java [hunk 4]
```diff
@@ -67,6 +69,7 @@ public void after() {
     }
 
     @Test
+    @DisabledOnOs(OS.WINDOWS)
```
Comment (trentjeff) [inline nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/tests/integration/client/HttpProxyTest.java:72]: same here

File: builder/tests/builder/src/test/java/io/helidon/builder/test/CustomNamedTest.java [hunk 5]
```diff
@@ -54,7 +54,14 @@ void testIt() throws Exception {
                 .configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
         DefaultPrettyPrinter printer = new DefaultPrettyPrinter();
         String json = mapper.writer(printer).writeValueAsString(customNamed);
-        assertThat(json, equalTo("{\n" + "  \"stringSet\" : [ \"b\", \"a\", \"y\" ]\n" + "}"));
```
[the remark this answers is not in the document]
Comment (tvallin) [reply builder/tests/builder/src/test/java/io/helidon/builder/test/CustomNamedTest.java:59]: I am not sure that setting JVM properties is a good thing as it can have side effect on other part of the code.

File: inject/processor/src/main/java/io/helidon/inject/processor/ActiveProcessorUtils.java [hunk 6]
```diff
@@ -256,4 +256,11 @@ private Optional<ModuleInfoDescriptor> tryFindModuleInfoTheConventionalWay(Stand
         return Optional.empty();
     }
 
+    private static String normalizePath(String value) {
```
[the remark this answers is not in the document]
Comment (tvallin) [reply inject/processor/src/main/java/io/helidon/inject/processor/ActiveProcessorUtils.java:259]: Done

**Comment by tvallin** [comment]
This is ready for review 👍

File: tests/integration/packaging/mp-1/src/test/java/io/helidon/tests/integration/packaging/mp1/Mp1JlinkTestIT.java
Comment (romain-grecourt) [inline tests/integration/packaging/mp-1/src/test/java/io/helidon/tests/integration/packaging/mp1/Mp1JlinkTestIT.java:1]: No changes in this file.

File: tests/integration/packaging/inject/src/test/java/io/helidon/tests/integration/packaging/inject/InjectJlinkTestIT.java
Comment (romain-grecourt) [inline tests/integration/packaging/inject/src/test/java/io/helidon/tests/integration/packaging/inject/InjectJlinkTestIT.java:1]: No changes in this file.

File: webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcClientUriTest.java [hunk 7]
```diff
@@ -77,6 +79,7 @@ void testSupplier() {
      * Should fail to connect to first URI but succeed with second after retrying.
      */
     @Test
+    @DisabledOnOs(value = OS.WINDOWS, disabledReason = "Windows runner is too slow")
```
Comment (romain-grecourt) [inline webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcClientUriTest.java:82]: Can we update the test to handle slow runners ?
Should we file an issue for this ?

Comment (tvallin) [reply webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcClientUriTest.java]: Test updated !

File: .github/actions/common/action.yml [hunk 8]
```diff
@@ -141,7 +141,7 @@ runs:
       shell: bash
     - name: Archive test results
       # https://github.com/actions/upload-artifact/issues/240
```
Comment (romain-grecourt) [inline .github/actions/common/action.yml:143]: Remove the comment with the issue, as it's not applicable anymore.

**Review by romain-grecourt — APPROVED** [review]
