### PR TITLE
4.x: Update all module to be compilable and testable with Java 24.

### LINKED ISSUE #9860: 4.x: Helidon build fails with Java 24
There are two problems:

1. Incorrect processing of error types in `AptTypeFactory`, where an inner type without a package does not resolve into a proper class name
2. Micronaut Data integration fails at test compile, due to a problem with one of the Micronaut annotation processors (under investigation, will reference issue)

As a result the repo cannot be built using Java 24 (using build 36 to validate).

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #9860 

Updates that allow us to build and test using Java 24

Some tests are disabled in Java 24 (where we need to handle external libraries), some are updated to have a different behavior on Java 21 and 24.

A few changes were done to allow work on both versions.

### CODE REVIEW

File: webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HeadersServerTest.java [hunk 1]
```diff
@@ -203,20 +203,32 @@ void serverInbound(WebServer server) throws IOException, InterruptedException {
...
+            }
+
+            // There is no way how to access GO_AWAY status code and additional data with JDK Http client
+            try {
+                HttpResponse<String> response = client.send(req.uri(base.resolve("/cont-in")).build(),
+                                                            HttpResponse.BodyHandlers.ofString());
+
+                int status = response.statusCode();
+                // since Java 24, we get a 400 back and not an exception
+                assertThat("IOException or status 400 was expected, but go status " + response.statusCode()
```
Comment (danielkec) [inline webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HeadersServerTest.java:223]:
```suggestion
                assertThat("IOException or status 400 was expected, but got status " + response.statusCode()
```

**Review by danielkec — CHANGES_REQUESTED** [review]

**Review by danielkec — APPROVED** [review]

**Review by barchetta — APPROVED** [review]
