### PR TITLE
Error handling removed from the filter chain

### LINKED ISSUE #5394: Nima: Filters error handling
Filters - error handling is probably done for each filter separately, check if this could be simplified (see stack trace in a handler).

There is a chance that this cannot be changed, but it does create quite a deep stack trace...

### PR DESCRIPTION
**Pull request by Verdent**
Fixes #5394

### CODE REVIEW

File: nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/Filters.java [hunk 1]
```diff
@@ -111,7 +116,7 @@ public void proceed() {
                 return;
             }
             if (filters.hasNext()) {
-                errorHandlers.runWithErrorHandling(ctx, request, response, this::runNextFilter);
+                filters.next().filter(this, request, response);
```
Comment (tomas-langer) [inline nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/Filters.java:119]: The problem I see with this new approach is that if an error handler is executed for routing, it would get executed again for the whole `executeFilters` once again.

I think that if the same exception that was thrown from routing would enter the second error handler (for filtering), the error handler should not be executed (same instance of exception).

**Review by tomas-langer — CHANGES_REQUESTED** [review]

**Review by tomas-langer — APPROVED** [review]
