### PR TITLE
4.x Allow programmatic look-up of MetricRegistry via CDI without NPE

### LINKED ISSUE #8209: 4.x `CDI.current().select(MetricRegistry.class).get()` throws NPE
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Attempting a programmatic look-up of `MetricRegistry` triggers an NPE.

## Steps to reproduce
1. In the MP QuickStart app, add the following line at the beginning of `GreetResource#getDefaultMessage`:
   ```
   MetricRegistry appRegistry = CDI.current().select(MetricRegistry.class).get();
   ```
2. `mvn clean package`
The unit tests fail because of an NPE in `RegistryProducer` because the producer method assumes the `InjectionPoint` passed is non-null as is its `getAnnotated()` value but in this case `getAnnotated()` is, reasonably, null.

### PR DESCRIPTION
**Pull request by tjquinno**
### Description
Resolves #8209 

The producer method failed to check that the injection point and its `getAnnotated()` return value were non-null before using them.  Thus `CDI.current().select(MetricRegistry.class).get()` triggered an NPE.

(It turned out that the `InjectionPoint` passed is non-null but its `getAnnotated()` return value _was_ null in this case.)

### Documentation
Bug fix - no doc impact

### CODE REVIEW

File: microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/ProducerTest.java [hunk 1]
```diff
@@ -89,4 +90,12 @@ void testRegistryFactoryProducer() {
         MetricRegistry customRegistry = registryFactory.getRegistry("myCustomScope");
         assertThat("Custom scoped MetricRegistry", customRegistry, notNullValue());
     }
+
+    @Test
+    void testDirectMetricRegistryLookup() {
+        MetricRegistry appRegistry = CDI.current().select(MetricRegistry.class).get();
+        assertThat("Directly-looked-up app registry", appRegistry, notNullValue());
+
```
Comment (spericas) [inline microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/ProducerTest.java:98]: Empty lines?

File: microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java [hunk 2]
```diff
@@ -40,7 +41,8 @@ private RegistryProducer() {
     @Produces
     @Default
     public static org.eclipse.microprofile.metrics.MetricRegistry getScopedRegistry(InjectionPoint injectionPoint) {
-        RegistryScope scope = injectionPoint.getAnnotated().getAnnotation(RegistryScope.class);
+        Annotated annotated = injectionPoint == null ? null : injectionPoint.getAnnotated();
+        RegistryScope scope = annotated == null ? null : annotated.getAnnotation(RegistryScope.class);
```
Comment (spericas) [inline microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java:45]: Minor, parentheses around condition help readability in this case IMO.

File: microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/ProducerTest.java (hunk 1 above)
Comment (tjquinno) [reply microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/ProducerTest.java:98]: Fixed

File: microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java (hunk 2 above)
Comment (tjquinno) [reply microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java]: Changed

**Review by spericas — APPROVED** [review]
