### PR TITLE
Http/2 revamp

### LINKED ISSUE #9272: h2spec http2 8.1.2.6 fails
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.1.1

----------

## Problem Description
```
  8. HTTP Message Exchanges
    8.1. HTTP Request/Response Exchange
      8.1.2. HTTP Header Fields
        8.1.2.6. Malformed Requests and Responses
          using source address 127.0.0.1:59750
          × 1: Sends a HEADERS frame with the "content-length" header field which does not equal the DATA frame payload length
            -> The endpoint MUST treat this as a stream error of type PROTOCOL_ERROR.
               Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                         RST_STREAM Frame (Error Code: PROTOCOL_ERROR)
                         Connection closed
                 Actual: DATA Frame (length:2, flags:0x01, stream_id:1)
          using source address 127.0.0.1:59752
          × 2: Sends a HEADERS frame with the "content-length" header field which does not equal the sum of the multiple DATA frames payload length
            -> The endpoint MUST treat this as a stream error of type PROTOCOL_ERROR.
               Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                         RST_STREAM Frame (Error Code: PROTOCOL_ERROR)
                         Connection closed
                 Actual: DATA Frame (length:2, flags:0x01, stream_id:1)
```

### PR DESCRIPTION
**Pull request by danielkec**
Fixes #9272, #9273 and #9282

- Add h2spec test
- Consuming request trailers
- Larger frame splitting fix
- Flow control update timeout
- Streamed payload larger than content length discovery

### CODE REVIEW

File: http/http2/src/main/java/io/helidon/http/http2/Http2ConnectionWriter.java [hunk 1]
```diff
@@ -143,24 +142,14 @@ public int writeHeaders(Http2Headers headers,
...
-
-            writeData(dataFrame, flowControl);
-            bytesWritten += Http2FrameHeader.LENGTH;
-            bytesWritten += dataFrame.header().length();
-
-            return bytesWritten;
-        } finally {
-            streamLock.unlock();
-        }
+        // Executed on stream thread
```
Comment (spericas) [inline http/http2/src/main/java/io/helidon/http/http2/Http2ConnectionWriter.java:145]: Could you explain why the mutual exclusion is no longer needed here?

File: http/http2/src/main/java/io/helidon/http/http2/WindowSizeImpl.java [hunk 2]
```diff
@@ -146,21 +143,51 @@ public long incrementWindowSize(int increment) {
...
             while (getRemainingWindowSize() < 1) {
                 try {
-                    updated.get().get(timeoutMillis, TimeUnit.MILLISECONDS);
-                } catch (InterruptedException | ExecutionException | TimeoutException e) {
-                    if (LOGGER_OUTBOUND.isLoggable(DEBUG)) {
-                        LOGGER_OUTBOUND.log(DEBUG,
-                                            String.format("%s OFC STR %d: Window depleted, waiting for update.", type, streamId));
-                    }
+                    updatedSemaphore.drainPermits();
+                    var ignored = updatedSemaphore.tryAcquire(Math.min(backoff, 5000), TimeUnit.MILLISECONDS);
```
Comment (spericas) [inline http/http2/src/main/java/io/helidon/http/http2/WindowSizeImpl.java:171]: Maybe create some backoff constants for the upper and lower bounds?

File: http/http2/src/main/java/io/helidon/http/http2/Http2ConnectionWriter.java (hunk 1 above)
Comment (danielkec) [reply http/http2/src/main/java/io/helidon/http/http2/Http2ConnectionWriter.java:145]: Because method is executed only from a single stream thread only, lock was actually causing a deadlock when stream was expecting flow-control window update(wating for update blocks stream thread). Headers needs to be followed by data only from a single stream point of view, other frames from other streams needs and can be writable between those two.

**Review by spericas — APPROVED** [review]

**Review by tomas-langer — APPROVED** [review]
