### PR TITLE
Fix http2 client dynamic table RC #10820

### LINKED ISSUE #10820: [4.x] RC in http2 client inbound dynamic table
## Environment Details
* Helidon Version: 4.3.1

----------

## Problem Description
Http2 client uses connection wide dynamic table, table evicts oldest headers when there is not enough space to add/cache new header. This operation can be triggered when client reads headers and that can happen by design on different threads.

### PR DESCRIPTION
**Pull request by danielkec**
Fixes #10820

### CODE REVIEW

File: webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java [hunk 1]
```diff
@@ -477,13 +477,10 @@ private void continue100(Http2Headers headers, boolean endOfStream) {
...
 
     private Http2Headers readHeaders(Http2HuffmanDecoder decoder, boolean mergeWithPrevious) {
-        Http2Headers http2Headers = Http2Headers.create(this,
-                                                        connection.getInboundDynamicTable(),
-                                                        decoder,
-                                                        mergeWithPrevious && currentHeaders != null
-                                                                ? currentHeaders
-                                                                : Http2Headers.create(WritableHeaders.create()),
-                                                        continuationData.toArray(new Http2FrameData[0]));
+        Http2Headers http2Headers = connection.readHeaders(this, decoder, mergeWithPrevious && currentHeaders != null
```
Comment (tomas-langer) [inline webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java]: Please fix formatting - each parameter should be on a separate line.

Comment (danielkec) [reply webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java]: Fixed

**Review by tomas-langer — APPROVED** [review]
