### PR TITLE
4.x: Cached connection close detection

### LINKED ISSUE #7367: 4.x: Http1Client detect broken connection
## Environment Details
* Helidon Version: 4.x

----------

## Problem Description
Http1 client needs to be able to detect severed connection. 

## Steps to reproduce
```java
        WebServer webServer = null;
        try {
            HttpRouting routing = HttpRouting.builder()
                    .route(POST, (req, res) -> res.send())
                    .build();

            webServer = WebServer.builder()
                    .routing(routing)
                    .build()
                    .start();

            int port = webServer.port();

            WebClient webClient = WebClient.builder()
                    .keepAlive(true)
                    .baseUri("http://localhost:" + port)
                    .build();

            try (var res = webClient.post().submit("WHATEVER")) {
                assertThat(res.status(), is(Http.Status.OK_200));
            }

            webServer.stop();
            webServer = WebServer.builder()
                    .port(port)
                    .routing(routing)
                    .build()
                    .start();

            try (var res = webClient.post().submit("WHATEVER")) {
                assertThat(res.status(), is(Http.Status.OK_200));
            }
        } finally {
            if (webServer != null) {
                webServer.stop();
            }
        }
```

### PR DESCRIPTION
**Pull request by danielkec**
Fixes: 

- #7367
- #7224
- #7225
- #7241

### CODE REVIEW

**Comment by danielkec** [comment]
Follow-up issue #7427

File: webclient/tests/http1/src/test/java/io/helidon/webclient/tests/SharedCacheTest.java [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+import io.helidon.webserver.http.HttpRouting;
+import io.helidon.webserver.http1.Http1Route;
+
+import org.junit.jupiter.api.Test;
+
+import static io.helidon.http.Http.Method.POST;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.is;
+
+public class SharedCacheTest {
```
Comment (tomas-langer) [inline webclient/tests/http1/src/test/java/io/helidon/webclient/tests/SharedCacheTest.java:31]: please make the class package local.

File: webserver/tests/upgrade/src/test/java/io/helidon/webserver/tests/upgrade/test/SharedHttp2CacheTest.java [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+import io.helidon.webserver.http.HttpRouting;
+import io.helidon.webserver.http2.Http2Route;
+
+import org.junit.jupiter.api.Test;
+
+import static io.helidon.http.Http.Method.POST;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.is;
+
+public class SharedHttp2CacheTest {
```
Comment (tomas-langer) [inline webserver/tests/upgrade/src/test/java/io/helidon/webserver/tests/upgrade/test/SharedHttp2CacheTest.java:33]: remove public

**Review by tomas-langer — APPROVED** [review]
