### PR TITLE
Fix incorrect tags comparison when trying to match metric IDs

### LINKED ISSUE #5541: MetricRegistry::counter inconsistent result with multiple tags
## Environment Details
* Helidon Version: 3.0.*
* Helidon SE or Helidon MP: MP
* JDK version: openjdk 17.0.4 2022-07-19
* OS: Debian 11

----------

## Problem Description
`MetricRegistry::counter` does not return consistent result when you have more than 1 tag specified.
It seems that the order in which you provide these tags affects the behavior. If your tags are alphabetically sorted, then you get the same counter every time you call the method. But if you have tags in non-alphabetical order, then seemingly you get a new instance of a counter every time you call the method.
Expected Behavior: when calling `MetricRegsitry::counter` with some string and a set of tags, regardless of the order of tags, you should get the same counter object back.
```
Counter counter1 = metricRegistry.counter("myCounter" , new Tag("foo", "1"),  new Tag("bar", "1"));
Counter counter2 = metricRegistry.counter("myCounter" , new Tag("foo", "1"),  new Tag("bar", "1"));
Counter counter3 = metricRegistry.counter("myCounter" , new Tag("bar", "1"),  new Tag("foo", "1"));

// These will fail
assertEquals(counter1, counter2);
assertEquals(counter1, counter3);

// In practice
Counter counter4 = metricRegistry.counter("myCounter" , new Tag("bar", "1"),  new Tag("foo", "1"));
assertEquals(counter3, counter4);  // This will be true
```

## Steps to reproduce
Adding tests below makes build fail on my local machine. (These are not exactly `MetricRegsitry` Tests, but I believe it's part of the same bug?)
```
$ git --no-pager diff HEAD
diff --git a/metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java b/metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java
index d6930dc26..cbce25c63 100644
--- a/metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java
+++ b/metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java
@@ -22,6 +22,7 @@ import org.eclipse.microprofile.metrics.MetricType;
 import org.eclipse.microprofile.metrics.SimpleTimer;
 import org.eclipse.microprofile.metrics.Tag;
 import org.junit.jupiter.api.Test;
+import static org.junit.jupiter.api.Assertions.assertEquals;
 import static org.junit.jupiter.api.Assertions.assertThrows;

 class MetricStoreTests {
@@ -56,4 +57,92 @@ class MetricStoreTests {
         assertThrows(IllegalArgumentException.class, () ->
                 store.getOrRegisterMetric(meta2, Counter.class, NO_TAGS));
     }
+
+    @Test
+    void testAvoidDuplicates() {
+        Metadata meta1 = Metadata.builder()
+                .withName("a")
+                .withType(MetricType.COUNTER)
+                .build();
+
+        NoOpMetricRegistry registry = NoOpMetricRegistry.create(MetricRegistry.Type.APPLICATION);
+
+        MetricStore<NoOpMetric> store = MetricStore.create(REGISTRY_SETTINGS,
+                                                           NoOpMetricRegistry.NO_OP_METRIC_FACTORIES,
+                                                           null,
+                                                           null,
+                                                           MetricRegistry.Type.APPLICATION,
+                                                           NoOpMetric.class,
+                                                           registry::toImpl);
+
+        Counter counter1 = store.getOrRegisterMetric(meta1, Counter.class, NO_TAGS);
+        Counter counter2 = store.getOrRegisterMetric(meta1, Counter.class, NO_TAGS);
+        assertEquals(counter1, counter2);
+    }
+    @Test
+    void testAvoidDuplicates1() {
+        Tag[] TAGS = {new Tag("foo", "1")};
+        Metadata meta1 = Metadata.builder()
+                .withName("a")
+                .withType(MetricType.COUNTER)
+                .build();
+
+        NoOpMetricRegistry registry = NoOpMetricRegistry.create(MetricRegistry.Type.APPLICATION);
+
+        MetricStore<NoOpMetric> store = MetricStore.create(REGISTRY_SETTINGS,
+                                                           NoOpMetricRegistry.NO_OP_METRIC_FACTORIES,
+                                                           null,
+                                                           null,
+                                                           MetricRegistry.Type.APPLICATION,
+                                                           NoOpMetric.class,
+                                                           registry::toImpl);
+
+        Counter counter1 = store.getOrRegisterMetric(meta1, Counter.class, TAGS);
+        Counter counter2 = store.getOrRegisterMetric(meta1, Counter.class, TAGS);
+        assertEquals(counter1, counter2);
+    }
+    @Test
+    void testAvoidDuplicates2() {
+        Tag[] TAGS = {new Tag("foo", "1"), new Tag("bar", "1")};
+        Metadata meta1 = Metadata.builder()
+                .withName("a")
+                .withType(MetricType.COUNTER)
+                .build();
+
+        NoOpMetricRegistry registry = NoOpMetricRegistry.create(MetricRegistry.Type.APPLICATION);
+
+        MetricStore<NoOpMetric> store = MetricStore.create(REGISTRY_SETTINGS,
+                                                           NoOpMetricRegistry.NO_OP_METRIC_FACTORIES,
+                                                           null,
+                                                           null,
+                                                           MetricRegistry.Type.APPLICATION,
+                                                           NoOpMetric.class,
+                                                           registry::toImpl);
+
+        Counter counter1 = store.getOrRegisterMetric(meta1, Counter.class, TAGS);
+        Counter counter2 = store.getOrRegisterMetric(meta1, Counter.class, TAGS);
+        assertEquals(counter1, counter2);
+    }
+    @Test
+    void testAvoidDuplicates3() {
+        Tag[] TAGS = {new Tag("foo", "1"), new Tag("bar", "1"), new Tag("baz", "1")};
+        Metadata meta1 = Metadata.builder()
+                .withName("a")
+                .withType(MetricType.COUNTER)
+                .build();
+
+        NoOpMetricRegistry registry = NoOpMetricRegistry.create(MetricRegistry.Type.APPLICATION);
+
+        MetricStore<NoOpMetric> store = MetricStore.create(REGISTRY_SETTINGS,
+                                                           NoOpMetricRegistry.NO_OP_METRIC_FACTORIES,
+                                                           null,
+                                                           null,
+                                                           MetricRegistry.Type.APPLICATION,
+                                                           NoOpMetric.class,
+                                                           registry::toImpl);
+
+        Counter counter1 = store.getOrRegisterMetric(meta1, Counter.class, TAGS);
+        Counter counter2 = store.getOrRegisterMetric(meta1, Counter.class, TAGS);
+        assertEquals(counter1, counter2);
+    }
 }
```

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #5541 

The original code used an array comparison to compare the tags of a previously-registered metric with the tags of a candidate new metric.

Inside the MicroProfile Metrics implementation of `MetricID` the tags are stored in a `TreeMap`. So iterators deliver in key-order (that is, in order of ascending tag name). But the comparison in `MetricStore` did not order the candidate metric's tag array by tag name prior to comparing. Tag sets that should match might not, depending on the order in which the tags were specified in the array.

The PR just creates a temporary `TreeMap` to hold the candidate tags so it can compare that and the `MetricID`'s `TreeMap` directly. Metric registration is typically a relatively infrequent event, so creating the `TreeMap` for this purpose should not hurt performance noticeably.

(BTW, this is not an issue in 2.x because the implementation is different and that code created a candidate `MetricID` for each candidate new metric and our code compared the two `MetricID`s which did the right thing with the tags.)

### CODE REVIEW

File: metrics/api/src/main/java/io/helidon/metrics/api/MetricStore.java [hunk 1]
```diff
@@ -556,6 +556,14 @@ private <S> S access(Lock lock, Callable<S> action) {
         }
     }
 
+    private static boolean tagsMatch(Tag[] tags, Map<String, String> tagMap) {
+        Map<String, String> newTags = new TreeMap<>();
```
Comment (barchetta) [inline metrics/api/src/main/java/io/helidon/metrics/api/MetricStore.java:560]: I was wondering if this should optimize for the case of a single tag (to avoid creating the Map), but now I see you mention in the description that this is an infrequent operation. So LGTM!

**Review by barchetta — APPROVED** [review]
