### PR TITLE
11430: Fix bulkhead waiting metric accounting

### LINKED ISSUE #11430: Bulkhead metrics race condition
Bulkhead metrics fails tests intermittently due to a race condition.

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #11430

Fix bulkhead queue metric accounting so `ft.bulkhead.executionsWaiting` stays incremented while a queued call is actually blocked, and add regression coverage for the previous behavior.

### CODE REVIEW

File: fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadImpl.java [hunk 1]
```diff
@@ -132,28 +132,36 @@ public <T> T invoke(Supplier<? extends T> supplier) {
...
-            } finally {
-                try {
-                    if (metricsEnabled) {
-                        waitingDurationMetric.record(System.nanoTime() - start, TimeUnit.NANOSECONDS);
-                        callsWaiting.decrementAndGet();
-                    }
-                } finally {
-                    inProgressLock.unlock(); // we have enqueued, now we can wait
+                if (waitingCounted) {
+                    waitingDurationMetric.record(System.nanoTime() - start, TimeUnit.NANOSECONDS);
```
Comment (danielkec) [inline fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadImpl.java]: `waitingDuration` is still recorded before `barrier.waitOn()`, so it measures enqueue time, not the actual time spent waiting to enter the bulkhead.

File: fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadImpl.java [hunk 2]
```diff
@@ -131,29 +131,37 @@ public <T> T invoke(Supplier<? extends T> supplier) {
...
+                callsRejected.incrementAndGet();
                 throw new BulkheadException("Bulkhead queue \"" + name + "\" is full");
             }
-            barrier.waitOn();
+            long waitStartedAt = 0L;
+            if (waitingCounted) {
+                waitStartedAt = System.nanoTime();
+            }
+            try {
+                barrier.waitOn();
```
Comment (danielkec) [inline fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadImpl.java]: Since `cancelSupplier()` now retracts the same barrier, waking up here no longer guarantees the caller actually acquired the permit. The code below still calls `dequeued()` before checking `cancelledSuppliers`, so cancelled queued calls report a dequeue event even though they never run. I think the fix is to move the listener notification after the cancellation check, for example:

```java
if (cancelledSuppliers.remove(supplier)) {
    return null;
}
listeners.forEach(l -> l.dequeued(supplier));
```

Comment (spericas) [reply fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadImpl.java]: Indeed
